- kaltura-ui/src/index.ts
- kaltura-ui/src/kaltura-ui.module.ts
- kaltura-ui/src/player/player.component.html
- kaltura-ui/src/player/player.component.scss
- kaltura-ui/src/player/player.component.ts
> feat: player component supporting dynamic embed and API

- kaltura-primeng-ui/src/directives/datatable-fillheight.ts
- [] Bugfix
Add ability to conditionally turn on/off directive
- [] Yes
---
> feat: add ability conditionally to switch directive

- kaltura-primeng-ui/src/auto-complete/auto-complete.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-ng/9)
> prepare to production deployment

- kaltura-primeng-ui/src/directives/datatable-fillheight.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-ng/10)
> Entries list refactoring

- kaltura-ui/src/details-bar/detail-info.component.html
- kaltura-ui/src/details-bar/detail-info.component.scss
- kaltura-ui/src/details-bar/detail-info.component.ts
- kaltura-ui/src/details-bar/details-bar.component.html
- kaltura-ui/src/details-bar/details-bar.component.scss
- kaltura-ui/src/details-bar/details-bar.component.ts
- kaltura-ui/src/details-bar/details-bar.module.ts
- kaltura-ui/src/details-bar/index.ts
- kaltura-ui/src/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-ng/13)
> Details bar

- kaltura-ui/src/area-blocker/area-blocker.component.scss
- [] Feature
- [] Yes
- [] No
---
--- …
> fix: allow to show new lines in areablocker message

- kaltura-client/package-lock.json
- kaltura-client/package.json
- kaltura-common/src/upload-management/upload-file-adapter.ts
- kaltura-common/src/upload-management/upload-management.service.ts
- kaltura-server-utils/package-lock.json
- kaltura-server-utils/package.json
- kaltura-server-utils/src/upload-management/kaltura-upload-adapter.service.ts
- kaltura-server-utils/src/upload-management/kaltura-upload-file.ts
- [] Bugfix
- [] Yes
- [] No
---
--- …
> Resume upload

- kaltura-primeng-ui/src/auto-complete/auto-complete.component.scss
**What kind of change does this PR introduce?** (checkone with "x")
- [] Feature
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-ng/20)
> KMCNG-677 Long tags are not displayed properly

- kaltura-primeng-ui/src/auto-complete/auto-complete.component.html
- kaltura-primeng-ui/src/auto-complete/auto-complete.component.ts
> fix: KMCNG-822 - Entry details: Users - missing tooltips and data display

- kaltura-primeng-ui/src/auto-complete/auto-complete.component.html
- kaltura-primeng-ui/src/auto-complete/auto-complete.component.ts
> KMCNG-822 - Entry details: Users - missing tooltips and data display

- kaltura-ui/src/popup-widget/popup-widget.component.ts
- [] Bugfix
closeOnScroll input to close popupWidget on window scroll
- [] Yes
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-ng/32)
> feat: add `closeOnScroll` option to popup widget

- kaltura-ui/src/popup-widget/popup-widget.component.scss
- kaltura-ui/src/popup-widget/popup-widget.component.ts
- [] Bugfix
Adding editmodal input option to popup widget
using css calc property will also support window resizing for height matters.
- [] Yes
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-n …
> feat: add edit mode modal to popup widget

- kaltura-common/src/upload-management/upload-management.service.ts
- kaltura-primeng-ui/src/auto-complete/auto-complete.component.ts
- [] Bugfix
- [] Feature
- [] Yes
- [] No
---
--- …
> feat: add getTrackedFile function

- kaltura-ui/src/components/scroll-to-top-container.component.ts
- kaltura-ui/src/kaltura-ui.module.ts
- [] Bugfix
- [] Feature
- [] Yes
- [] No
---
--- …
> feat: add scroll to top container component

- kaltura-ui/src/validators/validators.ts
> Have added a new method "isUrlValid" to the KalturaValidators class

- kaltura-ui/src/area-blocker/area-blocker.component.html
- kaltura-ui/src/area-blocker/area-blocker.component.ts
- [] Bugfix
k-area-blocker can accept class names as input to allow further customization. 
- [] Yes
---
---
This change …
> KMS-15911 allow passing class names to area blocker component

- kaltura-ui/src/index.ts
- kaltura-ui/src/input-helper/index.ts
- kaltura-ui/src/input-helper/input-helper.component.html
- kaltura-ui/src/input-helper/input-helper.component.scss
- kaltura-ui/src/input-helper/input-helper.component.ts
- kaltura-ui/src/input-helper/input-helper.module.ts
- kaltura-ui/src/popup-widget/popup-widget.component.scss
- kaltura-ui/src/popup-widget/popup-widget.component.ts
- kaltura-ui/src/styles/scss/theme.scss
duplicate of https://github.com/kaltura/kaltura-ng/pull/36
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-ng/39)
> feat: input helper popover and auto-positioning functionality to popup widget

- kaltura-client/package-lock.json
- kaltura-client/package.json
- kaltura-server-utils/package-lock.json
- kaltura-server-utils/package.json
upgrade kaltura-client-typescript to include fixes for file upload
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-ng/43)
> chore: upgrade kaltura-typescript-client library

- kaltura-ui/src/area-blocker/area-blocker.component.html
- kaltura-ui/src/area-blocker/area-blocker.component.scss
- kaltura-ui/src/area-blocker/area-blocker.component.ts
> fix: fix loading spinner layout

- kaltura-primeng-ui/src/dynamic-form/dynamic-form.module.ts
- kaltura-primeng-ui/src/dynamic-form/prime-control.component.html
- kaltura-ui/src/dynamic-form/controls/index.ts
- kaltura-ui/src/dynamic-form/controls/switch-control.ts
- kaltura-ui/src/dynamic-form/dynamic-form-control-base.ts
- kaltura-ui/src/dynamic-form/dynamic-form-item.component.html
- kaltura-ui/src/dynamic-form/dynamic-form-item.component.ts
- kaltura-ui/src/dynamic-form/dynamic-form.service.ts
* add switch control type in prime-control
* add validators to dynamic form control
- [] Bugfix
- [] Yes
- [] No
---
--- …
> add validators to dynamic form control and create new control type

- kaltura-primeng-ui/src/dynamic-form/prime-control.component.html
- kaltura-primeng-ui/src/dynamic-form/prime-control.component.ts
- kaltura-ui/src/dynamic-form/dynamic-form-control-base.ts
- kaltura-ui/src/dynamic-form/dynamic-form-item.component.html
- kaltura-ui/src/dynamic-form/dynamic-form-item.component.ts
- kaltura-ui/src/input-helper/input-helper.component.html
* support input helper without title
- [] Bugfix
- [] Feature
- [] Yes
- [] No
---
--- …
> * add validation errors support

- kaltura-primeng-ui/src/dynamic-form/prime-control.component.ts
- kaltura-ui/src/dynamic-form/dynamic-form-item.component.ts
- [] Bugfix
- [] Feature
- [] Yes
- [] No
---
--- …
> code review changes

- kaltura-primeng-ui/src/dynamic-form/dynamic-form.module.ts
- kaltura-primeng-ui/src/dynamic-form/prime-control.component.html
- kaltura-primeng-ui/src/dynamic-form/prime-control.component.ts
- kaltura-ui/src/dynamic-form/controls/index.ts
- kaltura-ui/src/dynamic-form/controls/switch-control.ts
- kaltura-ui/src/dynamic-form/dynamic-form-control-base.ts
- kaltura-ui/src/dynamic-form/dynamic-form-item.component.html
- kaltura-ui/src/dynamic-form/dynamic-form-item.component.ts
- kaltura-ui/src/dynamic-form/dynamic-form.service.ts
- kaltura-ui/src/input-helper/input-helper.component.html
* add switch control type in prime-control
* add validators to dynamic form control
- [] Bugfix
- [] Yes
- [] No
---
--- …
> dynamic from control and validations and switch control type

- kaltura-primeng-ui/src/dynamic-form/prime-control.component.ts
- [] Bugfix
- [] Feature
- [] Yes
- [] No
---
--- …
> check is valid on init

- kaltura-ui/src/popup-widget/popup-widget.component.ts
> feat: center popups on resize

- kaltura-primeng-ui/src/dynamic-form/prime-control.component.ts
- kaltura-ui/src/dynamic-form/dynamic-form-item.component.html
- kaltura-ui/src/popup-widget/popup-widget.component.ts
- mc-shared/src/filters/filter-types/boolean-type.ts
- mc-shared/src/filters/filter-types/index.ts
- [] Bugfix
- [] Feature
- [] Yes
- [] No
---
--- …
> Dynamic form input helper should allow html

- kaltura-ui/src/area-blocker/area-blocker.component.ts
prevent runtime error when showing and hiding loader at the same event loop cycle
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-ng/63)
> handle show loader only if needed

- kaltura-ui/src/input-helper/input-helper.component.html
- kaltura-ui/src/input-helper/input-helper.component.ts
- [] Bugfix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-ng/64)
> kInputHelper - added 'click' trigger support

- kaltura-ui/src/dynamic-form/dynamic-form-item.component.html
- [] Bugfix
- [] Feature
- [] Yes
- [] No
---
--- …
> allow html content in input helper in dynamic form

- kaltura-primeng-ui/src/dynamic-form/prime-control.component.html
- kaltura-ui/src/dynamic-form/controls/index.ts
- kaltura-ui/src/dynamic-form/controls/number-control.ts
* dynamic form remove TextboxControlArgs
- [] Bugfix
- [] Feature
- [] Yes
- [] No
---
--- …
> * dynamic form add number control

- kaltura-common/src/xml-parser/xml-parser.ts
- [] Bugfix
- [] Feature
- [] Yes
- [] No
---
--- …
> xml-parser enchantments

- mc-shared/src/filters/filter-types/grouped-list-type.ts
- mc-shared/src/filters/filter-types/list-type.ts
- remove previous structure of list and group filters
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-ng/70)
> remove old filters of complex list and group of lists

- kaltura-primeng-ui/src/auto-complete/auto-complete.component.html
- kaltura-primeng-ui/src/auto-complete/auto-complete.component.ts
- [] Bugfix
- [] Feature
- [] Yes
- [] No
---
--- …
> item clicked autocomplete

- kaltura-common/package-lock.json
- kaltura-common/package.json
- kaltura-common/src/server-polls/server-polls.service.ts
- kaltura-logger/package-lock.json
- kaltura-logger/src/kaltura-logger.module.ts
- kaltura-logger/src/kaltura-logger.service.ts
- kaltura-primeng-ui/package-lock.json
- kaltura-ui/package-lock.json
- mc-shared/package-lock.json
- mc-theme/package-lock.json
to be tested with [the following PR](https://github.com/kaltura/kmc-ng/pull/347)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-ng/73)
> improve server polling logic and extend kalura logger

- kaltura-ui/src/dynamic-form/dynamic-form-item.component.html
- kaltura-ui/src/dynamic-form/dynamic-form-item.component.ts
- [] Bugfix
- [] Feature
- [] Yes
- [] No
---
--- …
> add support	for labels template in dynamic form item

- kaltura-ui/src/validators/validators.ts
- [] Bugfix
- [] Yes
- [] No
---
--- …
> Feat: http validator (reactive form)

- kaltura-common/src/utils/kaltura-utils.ts
- kaltura-common/src/xml-parser/xml-parser.ts
- package-lock.json
- [] Feature
- [] Yes
- [] No
---
--- …
> Fix custom metadata

- kaltura-primeng-ui/src/styles/fonts/kaltura-prime-ui/variables.scss
- mc-theme/themes/default/scss/primeng/theme.scss
> fix: priming icons

- kaltura-ui/src/draggable-data-table/column.component.ts
- kaltura-ui/src/draggable-data-table/draggable-data-table.component.html
- kaltura-ui/src/draggable-data-table/draggable-data-table.component.scss
- kaltura-ui/src/draggable-data-table/draggable-data-table.component.ts
- kaltura-ui/src/draggable-data-table/draggable-data-table.module.ts
- kaltura-ui/src/draggable-data-table/index.ts
- [] Bugfix
PrimeNG data-table does not provide drag and drop functionality 
Developed data-table that supports D&D functionality 
- [] Yes
---
**Any background context you …
> draggable-data-table - initial commit

- kaltura-ui/src/date.pipe.ts
- [] Bugfix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-ng/85)
> feat: added longDateOnly (MMMM D, YYYY) format to DatePipe

- kaltura-primeng-ui/src/time-spinner/time-spinner.component.scss
- [] Feature
In Firefox time spinner bottom arrow is cut
Time spinner bottom arrow isn't cut
- [] Yes
- [] No
---
---
This …
> Fix time spinner arrows styles

- kaltura-primeng-ui/src/auto-complete/auto-complete.component.ts
- [] Feature
https://kaltura.atlassian.net/browse/KMCNG-674
https://kaltura.atlassian.net/browse/KMCNG-1263
sorry, for branch name, made a mistake copying the wrong name 😞 
- [] Yes
- [] No
---
**How should this …
> KMCNG-674, KMCNG-1263

- kaltura-ui/src/input-autofocus.ts
- [] Feature
https://kaltura.atlassian.net/browse/KMCNG-1291
- [] Yes
- [] No
---
--- …
> KMCNG-1291

- kaltura-ui/src/draggable-data-table/draggable-data-table.component.html
- kaltura-ui/src/draggable-data-table/draggable-data-table.component.scss
- kaltura-ui/src/draggable-data-table/draggable-data-table.component.ts
- [] Bugfix
In D&D table there is no next functionality:
- selectable
- multi d&d
- indexes  
- pagination 
- Multi d&d
- Pagination
- Selecable
- Indexes
- [] No
**Added APIs:**
1. [paginator] - boolean - to enable pagination functionality. 
2. …
> Extensive drag and drop master

- kaltura-ui/src/dynamic-form/dynamic-form-item.component.html
- [] Feature
https://kaltura.atlassian.net/browse/KMCNG-1461
- [] Yes
- [] No
---
--- …
> KMCNG-1461

- kaltura-primeng-ui/src/dynamic-form/dynamic-form.module.ts
- kaltura-primeng-ui/src/dynamic-form/prime-control.component.html
- kaltura-primeng-ui/src/dynamic-form/prime-list-options.pipe.ts
- kaltura-primeng-ui/src/multi-select/multi-select.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-ng/103)
> use kaltura multi select component in dynamic form

- kaltura-logger/src/kaltura-logger.service.ts
- [] Feature
Cannot build kaltura-ng due to a build error
Fix a build error, provide extended type declaration for the `trace` function
- [] Yes
- [] No
---
**Any …
> Fix logger trace arguments type declaration

- kaltura-ui/src/index.ts
- kaltura-ui/src/input-range/index.ts
- kaltura-ui/src/input-range/input-range.component.html
- kaltura-ui/src/input-range/input-range.component.scss
- kaltura-ui/src/input-range/input-range.component.ts
- kaltura-ui/src/input-range/input-range.module.ts
- [] Bugfix
- [] Feature
- [] Yes
- [] No
---
--- …
> add input range control

- kaltura-common/src/app-storage.service.ts
- kaltura-common/src/kaltura-common.module.ts
- kaltura-common/src/server-polls/server-polls.service.ts
- kaltura-logger/src/kaltura-logger-record.service.ts
- kaltura-logger/src/kaltura-logger.module.ts
- kaltura-logger/src/kaltura-logger.service.ts
- mc-shared/package-lock.json
- mc-shared/package.json
- mc-shared/src/components/power-user-console/index.ts
- mc-shared/src/components/power-user-console/power-user-console.component.html
- mc-shared/src/components/power-user-console/power-user-console.component.scss
- mc-shared/src/components/power-user-console/power-user-console.component.ts
- mc-shared/src/components/power-user-console/power-user-console.module.ts
- [] Bugfix
- [] Feature
Add logLevel validator function
- [] Yes
- [] No
---
--- …
> Extended logger support

- kaltura-ui/src/dynamic-form/dynamic-form-item.component.html
- kaltura-ui/src/tooltip/k-tooltip.directive.ts
- package-lock.json
- [] Bugfix
- [] Feature
https://trello.com/c/79delggq
- [] Yes
- [] No
---
--- …
> Tooltip adjustments

- kaltura-primeng-ui/src/clearable-input/clearable-input.component.html
- kaltura-primeng-ui/src/clearable-input/clearable-input.component.scss
- kaltura-primeng-ui/src/clearable-input/clearable-input.component.ts
- kaltura-primeng-ui/src/clearable-input/clearable-input.module.ts
- kaltura-primeng-ui/src/clearable-input/index.ts
- [] Bugfix
Add a component wrapper for input to support clear button option inside a text input.
- [] Yes
- [] No
---
--- …
> Add clearable input

- projects/kaltura-ng/kaltura-primeng-ui/src/lib/dynamic-form/prime-control.component.html
- [] Bugfix
- [] Feature
https://kaltura.atlassian.net/browse/KMCNG-1262
- [] Yes
- [] No
---
--- …
> KMCNG-1262

- kaltura-ui/src/tags/tags.component.ts
- [] Feature
https://kaltura.atlassian.net/projects/KMCNG/issues/KMCNG-1404
- [] Yes
- [] No
---
--- …
> KMCNG-1404

- projects/kaltura-ng/mc-theme/package-lock.json
- projects/kaltura-ng/mc-theme/themes/default/scss/primeng/theme.scss
- [] Bugfix
- [] Feature
Fix styles to support p-table
- [] Yes
- [] No
---
--- …
> refactor: PrimeNG new tables refactoring

- projects/kaltura-ng/kaltura-ui/src/lib/popup-widget/popup-widget.component.ts
https://kaltura.atlassian.net/browse/KMCNG-1955
- [] Yes
- [] No
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-ng/125)
> KMCNG-1955

- projects/kaltura-ng/mc-shared/src/lib/app-permissions/app-permissions-service-base.ts
- [] Bugfix
Allow boolean values in the `filterList` mapping
- [] Yes
- [] No
---
--- …
> Permissions enchancements

- projects/kaltura-ng/kaltura-common/src/lib/utils/kaltura-utils.ts
- projects/kaltura-ng/kaltura-common/src/lib/xml-parser/xml-parser.ts
- Please test this together with KMCNG-1995 branch in kmc-ng repo.
- try to load as many custom profiles as possible
- use merge instead of squash as the commit message include breaking change notification.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-ng/130)
> fix: custom metadata xml parsing and serializing KMCNG-1995

- projects/kaltura-ng/kaltura-primeng-ui/src/lib/dropdown/dropdown.component.html
- projects/kaltura-ng/kaltura-primeng-ui/src/lib/dropdown/dropdown.component.scss
- projects/kaltura-ng/kaltura-primeng-ui/src/lib/dropdown/dropdown.component.ts
- projects/kaltura-ng/kaltura-primeng-ui/src/lib/dropdown/dropdown.module.ts
- projects/kaltura-ng/kaltura-primeng-ui/src/lib/dropdown/index.ts
- projects/kaltura-ng/kaltura-primeng-ui/src/public_api.ts
- [] Bugfix
- [] Yes
- [] No
---
--- …
> Move custom dropdown component from tvm-ng project

- projects/kaltura-ng/mc-theme/themes/default/scss/_icons.scss
- projects/kaltura-ng/mc-theme/themes/default/scss/primeng/theme.scss
> fix: UI bug fixes

- projects/kaltura-ng/kaltura-primeng-ui/src/lib/dynamic-form/prime-control.component.html
- projects/kaltura-ng/kaltura-ui/src/lib/dynamic-form/dynamic-form-control-base.ts
- [] Bugfix
- [] Feature
https://kaltura.atlassian.net/browse/SUP-17876
- [] Yes
- [] No
---
> feat: support date format in dynamic date picker

- projects/kaltura-ng/kaltura-ui/src/lib/input-helper/input-helper.component.html
- projects/kaltura-ng/kaltura-ui/src/lib/input-helper/input-helper.component.ts
- [] Bugfix
- [] Feature
- [] Yes
- [] No
---
> trigger icon in inout helper component should be configurable

- projects/kaltura-ng/kaltura-primeng-ui/src/styles/scss/theme.scss
- projects/kaltura-ng/mc-theme/themes/default/scss/primeng/theme.scss
> fix: various style fixes

- projects/kaltura-ng/kaltura-primeng-ui/src/lib/auto-complete/auto-complete.component.html
- projects/kaltura-ng/kaltura-primeng-ui/src/lib/auto-complete/auto-complete.component.ts
- [] Feature
https://kaltura.atlassian.net/browse/NTVM-217
- [] Yes
---
> NTVM-217 fix scrolling in tag autocomplete in IE browser

- projects/kaltura-ng/kaltura-primeng-ui/src/lib/dynamic-form/prime-control.component.html
- projects/kaltura-ng/kaltura-ui/src/lib/dynamic-form/dynamic-form-control-base.ts
- projects/kaltura-ng/kaltura-ui/src/lib/dynamic-form/dynamic-form.service.ts
- [] Bugfix
- [] Feature
- [] Yes
- [] No
---
> feat: dynamic forms validation - provide custom validation trigger

- angular.json
- projects/kaltura-ng/kaltura-primeng-ui/polyfills.ts
- projects/kaltura-ng/kaltura-primeng-ui/src/lib/tiered-dropdown/index.ts
- projects/kaltura-ng/kaltura-primeng-ui/src/lib/tiered-dropdown/tiered-dropdown-sub/tiered-dropdown-sub.component.html
- projects/kaltura-ng/kaltura-primeng-ui/src/lib/tiered-dropdown/tiered-dropdown-sub/tiered-dropdown-sub.component.scss
- projects/kaltura-ng/kaltura-primeng-ui/src/lib/tiered-dropdown/tiered-dropdown-sub/tiered-dropdown-sub.component.ts
- projects/kaltura-ng/kaltura-primeng-ui/src/lib/tiered-dropdown/tiered-dropdown.component.html
- projects/kaltura-ng/kaltura-primeng-ui/src/lib/tiered-dropdown/tiered-dropdown.component.scss
- projects/kaltura-ng/kaltura-primeng-ui/src/lib/tiered-dropdown/tiered-dropdown.component.spec.ts
- projects/kaltura-ng/kaltura-primeng-ui/src/lib/tiered-dropdown/tiered-dropdown.component.ts
- projects/kaltura-ng/kaltura-primeng-ui/src/lib/tiered-dropdown/tiered-dropdown.module.ts
- projects/kaltura-ng/kaltura-primeng-ui/src/test.ts
- projects/kaltura-ng/kaltura-primeng-ui/tsconfig.spec.json
- [] Bugfix
- [] Feature
- [] Yes
- [] No
---
> tiredDropdown component

- projects/kaltura-ng/kaltura-primeng-ui/src/public_api.ts
- [] Bugfix
- [] Feature
- [] Yes
- [] No
---
> update public api

- projects/kaltura-ng/kaltura-primeng-ui/src/lib/tiered-dropdown/tiered-dropdown.module.ts
- [] Bugfix
- [] Feature
- [] Yes
- [] No
---
> fix module

- projects/kaltura-ng/mc-theme/themes/default/scss/primeng/theme.scss
> fix(datatable): add scroll to datatable KMCNG-2334

- projects/kaltura-ng/mc-theme/themes/default/scss/primeng/theme.scss
> fix(entries): radiobutton in filter preferences has a oval shape in IE11 KMCNG-2331

- projects/kaltura-ng/mc-theme/themes/default/scss/primeng/theme.scss
> fix(paginator): number of rows are truncated KMCNG-2329

- projects/kaltura-ng/mc-theme/themes/default/scss/primeng/theme.scss
> fix(entries): IE11 - datatable rows options has shifted down number KMCNG-2321

- projects/kaltura-ng/mc-theme/themes/default/scss/primeng/theme.scss
> fix(entries): IE11 - Scheduling - fields have wrong calendar button position KMCNG-2325

- projects/kaltura-ng/kaltura-primeng-ui/src/lib/auto-complete/auto-complete.component.ts
> fix(autocomplete): remove placeholder for not multiple on IE11 KMCNG-2324

- projects/kaltura-ng/mc-theme/themes/default/scss/primeng/theme.scss
> fix(checkbox): Green color box not aligned properly in check box KMCNG-2336

- projects/kaltura-ng/kaltura-primeng-ui/src/lib/draggable-data-table/draggable-data-table.component.scss
- projects/kaltura-ng/kaltura-primeng-ui/src/lib/multi-select/multi-select.component.scss
- projects/kaltura-ng/kaltura-primeng-ui/src/lib/slider/slider.component.scss
- projects/kaltura-ng/kaltura-primeng-ui/src/styles/fonts/kaltura-prime-ui/variables.scss
- projects/kaltura-ng/kaltura-ui/src/lib/details-bar/detail-info.component.scss
- projects/kaltura-ng/kaltura-ui/src/lib/popup-widget/popup-widget.component.scss
- projects/kaltura-ng/kaltura-ui/src/lib/tags/tag.component.scss
- projects/kaltura-ng/kaltura-ui/src/lib/tags/tags.component.scss
- projects/kaltura-ng/kaltura-ui/src/styles/scss/theme.scss
- projects/kaltura-ng/mc-theme/themes/default/scss/_base.scss
- projects/kaltura-ng/mc-theme/themes/default/scss/_variables.scss
- projects/kaltura-ng/mc-theme/themes/default/scss/primeng/theme.scss
>  fix(theme): change primary color, change backdrop color, change component colors to primary KMCNG-2370

- projects/kaltura-ng/mc-shared/src/lib/filters/filter-types/list-type.ts
> fix(filters base store/list filter): fix wrong comparison of arrays with the same length SUP-27709
